version: "3.9"

services:
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    command: npm start
    working_dir: /app-backend
    tty: true

  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db
    restart: 'always'